#  50. データの入手・整形

News Aggregator Data Setをダウンロードし、以下の要領で学習データ（train.txt），検証データ（valid.txt），評価データ（test.txt）を作成せよ．

1.ダウンロードしたzipファイルを解凍し，readme.txtの説明を読む．

2.情報源（publisher）が”Reuters”, “Huffington Post”, “Businessweek”, “Contactmusic.com”, “Daily Mail”の事例（記事）のみを抽出する．

3抽出された事例をランダムに並び替える．

4抽出された事例の80%を学習データ，残りの10%ずつを検証データと評価データに分割し，それぞれtrain.txt，valid.txt，test.txtというファイル名で保存する．ファイルには，１行に１事例を書き出すこととし，カテゴリ名と記事見出しのタブ区切り形式とせよ（このファイルは後に問題70で再利用する）

学習データと評価データを作成したら，各カテゴリの事例数を確認せよ．



In [1]:
#  データのダウンロード
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/00359/NewsAggregatorDataset.zip

--2023-06-07 10:10:59--  https://archive.ics.uci.edu/ml/machine-learning-databases/00359/NewsAggregatorDataset.zip
archive.ics.uci.edu (archive.ics.uci.edu) をDNSに問いあわせています... 128.195.10.252
archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443 に接続しています... 接続しました。
HTTP による接続要求を送信しました、応答を待っています... 200 OK
長さ: 29224203 (28M) [application/x-httpd-php]
`NewsAggregatorDataset.zip' に保存中

NewsAggregatorDatas 100%[===================>]  27.87M  5.53MB/s 時間 5.5s       

2023-06-07 10:11:05 (5.04 MB/s) - `NewsAggregatorDataset.zip' へ保存完了 [29224203/29224203]



In [1]:
import zipfile
zip_f =  zipfile.ZipFile('data/NewsAggregatorDataset.zip')
zip_list = zip_f.namelist()
print(zip_list)

['2pageSessions.csv', '__MACOSX/', '__MACOSX/._2pageSessions.csv', 'newsCorpora.csv', '__MACOSX/._newsCorpora.csv', 'readme.txt', '__MACOSX/._readme.txt']


In [2]:
#  readmeを読む
fp = zip_f.open('readme.txt', 'r')
readme_txt = fp.read()
txt = readme_txt.decode('shift_jis')
#print(txt)

In [3]:
!unzip data/NewsAggregatorDataset.zip

Archive:  data/NewsAggregatorDataset.zip
  inflating: 2pageSessions.csv       
   creating: __MACOSX/
  inflating: __MACOSX/._2pageSessions.csv  
  inflating: newsCorpora.csv         
  inflating: __MACOSX/._newsCorpora.csv  
  inflating: readme.txt              
  inflating: __MACOSX/._readme.txt   


In [4]:
!head data/newsCorpora.csv

1	Fed official says weak data caused by weather, should not slow taper	http://www.latimes.com/business/money/la-fi-mo-federal-reserve-plosser-stimulus-economy-20140310,0,1312750.story\?track=rss	Los Angeles Times	b	ddUyU0VZz0BRneMioxUPQVP6sIxvM	www.latimes.com	1394470370698
2	Fed's Charles Plosser sees high bar for change in pace of tapering	http://www.livemint.com/Politics/H2EvwJSK2VE6OF7iK1g3PP/Feds-Charles-Plosser-sees-high-bar-for-change-in-pace-of-ta.html	Livemint	b	ddUyU0VZz0BRneMioxUPQVP6sIxvM	www.livemint.com	1394470371207
3	US open: Stocks fall after Fed official hints at accelerated tapering	http://www.ifamagazine.com/news/us-open-stocks-fall-after-fed-official-hints-at-accelerated-tapering-294436	IFA Magazine	b	ddUyU0VZz0BRneMioxUPQVP6sIxvM	www.ifamagazine.com	1394470371550
4	Fed risks falling 'behind the curve', Charles Plosser says	http://www.ifamagazine.com/news/fed-risks-falling-behind-the-curve-charles-plosser-says-294430	IFA Magazine	b	ddUyU0VZz0BRneMioxUPQVP6sIxvM	www

In [5]:
#  FORMAT: ID \t TITLE \t URL \t PUBLISHER \t CATEGORY \t STORY \t HOSTNAME \t TIMESTAMP
#  となっているらしい
#  pandasのheaderをこれにしてみる
#  タブ区切りになっているのでread_table()を使う

In [1]:
#  特定のcsvファイルをpandasのデータフレームにする
import pandas as pd
import csv
filepath = 'data/newsCorpora.csv'
names = ['ID', 'TITLE', 'URL', 'PUBLISHER', 'CATEGORY', 'STORY', 'HOSTNAME', 'TIMESTAMP']
df = pd.read_table(filepath, names=names, header=None)

In [2]:
#  情報源（publisher）が”Reuters”, “Huffington Post”, “Businessweek”, “Contactmusic.com”, “Daily Mail”の事例（記事）のみを抽出する．
ch06_df = df[(df.PUBLISHER == 'Reuters') | (df.PUBLISHER == 'Huffington Post') | (df.PUBLISHER == 'Businessweek') | (df.PUBLISHER == 'Contactmusic.com') | (df.PUBLISHER == 'Daily Mail')]

In [3]:
#  ランダムに並び替える
ch06_df_random = ch06_df.sample(frac = 1)
ch06_df_random

ID                                              TITLE   
185182  185518  UPDATE 1-Astra gets lift in Pfizer fight as US...  \
332457  332917  Pharrell, Alsina, Nyong'o early winners at BET...   
1462      1463  GM recall probe team includes inside, outside ...   
259237  259683  UPDATE 2-Amazon says quick end unlikely in dis...   
388702  389162    10 Things You Didn’t Know About Charlie Sheen   
...        ...                                                ...   
22752    22753  Mick Jagger Issues Single Statement Regarding ...   
360386  360846  Pictured: The moment David Arquette proposes t...   
35799    35800  The Climate Post: Reports, Website Document Ef...   
161682  162018  Dozens of lost Warhol artworks discovered on A...   
165815  166151  Wounded Ukrainian mayor 'stable' in Israeli ho...   

                                                      URL         PUBLISHER   
185182  http://in.reuters.com/article/2014/05/06/astra...           Reuters  \
332457  http://www.reuters.com/article/2014/06/30/us-t...           Reuters   
1462    http://in.reuters.com/article/2014/03/10/autos...           Reuters   
259237  http://in.reuters.com/article/2014/05/28/amazo...           Reuters   
388702  http://www.contactmusic.com/in-depth/10-things...  Contactmusic.com   
...                                                   ...               ...   
22752   http://www.contactmusic.com/article/mick-jagge...  Contactmusic.com   
360386  http://www.dailymail.co.uk/tvshowbiz/article-2...        Daily Mail   
35799   http://www.huffingtonpost.com/tim-profeta/the-...   Huffington Post   
161682  http://www.dailymail.co.uk/news/article-261207...        Daily Mail   
165815  http://www.reuters.com/article/2014/04/29/us-u...           Reuters   

       CATEGORY                          STORY                HOSTNAME   
185182        b  db9i9C4vy1oSPJMIukbBh6rKgQNwM          in.reuters.com  \
332457        e  dbioztmajxtn9ZMTyQMMAgwGypQjM         www.reuters.com   
1462          t  d6oHu5PfuD_389MzHgrh61KXagXnM          in.reuters.com   
259237        b  dQXd3AV-9nc70hMkttTBaBFPxpeAM          in.reuters.com   
388702        e  dafAzhctSWlLL9MxlA9MoqeG9ZqqM    www.contactmusic.com   
...         ...                            ...                     ...   
22752         e  d00pSI3VqDUL5wMEU6vdcq2VFkgVM    www.contactmusic.com   
360386        e  d2e-11CoF-Ty_gMNknZmZ4ObmofNM     www.dailymail.co.uk   
35799         t  deNjFLy_uspUgDMEceMu1NZru1gSM  www.huffingtonpost.com   
161682        e  disIIjkl9ktVZZMpG7VrlACi26qLM     www.dailymail.co.uk   
165815        b  diF20GdN8avuFQMwsrPB9CbU6OOdM         www.reuters.com   

            TIMESTAMP  
185182  1399439904350  
332457  1404095289336  
1462    1394503087722  
259237  1401289646955  
388702  1405644452552  
...               ...  
22752   1395237073512  
360386  1404590970930  
35799   1395621550322  
161682  1398409620072  
165815  1398772290037  

[13340 rows x 8 columns]

In [4]:
#  まずは分割
from sklearn.model_selection import train_test_split
#  学習データと評価用データ（検証＆評価）に分割
ch06_train, ch06_test = train_test_split(ch06_df_random, train_size=0.8)
#  評価用データを検証と評価に分割
ch06_test, ch06_valid = train_test_split(ch06_test, test_size=0.5)

In [5]:
print(len(ch06_train))
print(len(ch06_test))
print(len(ch06_valid))

10672
1334
1334


In [8]:
ch06_train.value_counts('CATEGORY')

CATEGORY
b    4526
e    4208
t    1212
m     726
Name: count, dtype: int64

In [9]:
ch06_train[['TITLE', 'CATEGORY']].to_csv("work/train.txt", sep = '\t', header=None, index=False)
ch06_test[['TITLE', 'CATEGORY']].to_csv("work/test.txt", sep = '\t', header=None, index=False)
ch06_valid[['TITLE', 'CATEGORY']].to_csv("work/valid.txt", sep = '\t', header=None, index=False)

#  51. 特徴量抽出

学習データ，検証データ，評価データから特徴量を抽出し，それぞれtrain.feature.txt，valid.feature.txt，test.feature.txtというファイル名で保存せよ． なお，カテゴリ分類に有用そうな特徴量は各自で自由に設計せよ．記事の見出しを単語列に変換したものが最低限のベースラインとなるであろう．

In [52]:
from sklearn.feature_extraction.text import CountVectorizer
train_df = pd.read_table("work/train.txt", names=['TITLE', 'CATEGORY'], header=None)
valid_df = pd.read_table("work/valid.txt", names=['TITLE', 'CATEGORY'], header=None)
test_df = pd.read_table("work/test.txt", names=['TITLE', 'CATEGORY'], header=None)

# ベクトル化
count_vec = CountVectorizer(stop_words="english")
count_vec = count_vec.fit(train_df['TITLE'])

X_train = count_vec.transform(train_df['TITLE'])
X_valid = count_vec.transform(valid_df['TITLE'])
X_test = count_vec.transform(test_df['TITLE'])
print(type(X_train))
print(X_train.toarray())

<class 'scipy.sparse._csr.csr_matrix'>
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [53]:
#. 行列として保存
import numpy as np

np.savetxt('work/train.feature.txt', X_train.toarray())
np.savetxt('work/valid.feature.txt', X_valid.toarray())
np.savetxt('work/test.feature.txt', X_test.toarray())

In [54]:
#pd.DataFrame(X_train.toarray(), columns=count_vec.get_feature_names_out())
train_df.value_counts('CATEGORY')

CATEGORY
b    4526
e    4208
t    1212
m     726
Name: count, dtype: int64

In [55]:
# 　できているか確認
test = np.loadtxt('work/train.feature.txt')
print(count_vec.inverse_transform(test[:1]))
print(test[:1])

[array(['frankie', 'knuckles', 'letter', 'obamas', 'salute', 'trailblazer'],
      dtype='<U27')]
[[0. 0. 0. ... 0. 0. 0.]]


#  52. 学習

51で構築した学習データを用いて，ロジスティック回帰モデルを学習せよ．

In [56]:
#　　数値変換
def category_convert(x):
    if x == 'b':
        return 0
    elif x == 'e':
        return 1
    elif x == 't':
        return 2
    elif x == 'm':
        return 3
    else:
        assert Print('error')

In [57]:
#  それを訓練データに適応させて変換する
X_train = np.loadtxt('work/train.feature.txt')
Y_train = train_df["CATEGORY"].apply(category_convert)

In [58]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter=1000) 
model.fit(X_train, Y_train)

LogisticRegression(max_iter=1000)

In [59]:
#  精度を出してみる
print(model.score(X_train, Y_train))

0.9951274362818591


#  53. 予測

52で学習したロジスティック回帰モデルを用い，与えられた記事見出しからカテゴリとその予測確率を計算するプログラムを実装せよ．

In [2]:
#  予測
pred = model.predict(X_train)  
# 確率算出の際は、predict_proba()メソッドを利用
#  ラベル(クラス)の確率を知りたいケース
prob = model.predict_proba(X_train)

NameError: name 'model' is not defined

In [1]:
print(pred)
print(prob)

NameError: name 'pred' is not defined

#  54. 正解率の計測

52で学習したロジスティック回帰モデルの正解率を，学習データおよび評価データ上で計測せよ．

In [63]:
#  数値変換
Y_test = test_df["CATEGORY"].apply(category_convert)
Y_valid = valid_df["CATEGORY"].apply(category_convert)
#  明示的に
X_train = np.loadtxt('work/train.feature.txt')
X_test = np.loadtxt('work/test.feature.txt')

In [64]:
from sklearn.metrics import accuracy_score
Y_train_pred = model.predict(X_train)  
Y_test_pred = model.predict(X_test)
# 正解率
print('train_accuracy: ',  accuracy_score(Y_train, Y_train_pred))
print('test_accuracy: ',  accuracy_score(Y_test, Y_test_pred))

train_accuracy:  0.9951274362818591
test_accuracy:  0.9190404797601199


In [65]:
print(Y_train_pred)

[1 0 0 ... 3 1 1]


In [66]:
print(Y_test_pred)

[1 1 0 ... 0 0 1]


In [67]:
print(X_train)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [68]:
print(X_test)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
